# Generated by Django 5.0.6 on 2024-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Изображение'),
        ),
    ]
